package npm

import com.google.gson.GsonBuilder
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileSystemOperations
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import javax.inject.Inject

/**
 * 把模块的静态资源目录转换为可直接 pack/publish 的 npm 包目录。
 *
 * 源目录只保存业务文件，`package.json` 由任务根据稳定包名和 Gradle project.version 统一生成，
 * 避免静态文件中的版本与发布任务实际版本分离。
 */
@DisableCachingByDefault(because = "任务会清理并重新生成完整 npm 发布目录")
abstract class PrepareNpmStaticPackageTask : DefaultTask() {

  /** 不包含 package.json 的静态 npm 资源源集根目录。 */
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /** 最终可直接传给 npm CLI 的发布目录。 */
  @get:OutputDirectory
  abstract val outputDirectory: DirectoryProperty

  /** 生成到 package.json 的完整 npm 包名。 */
  @get:Input
  abstract val packageName: Property<String>

  /** 生成到 package.json 的精确版本。 */
  @get:Input
  abstract val packageVersion: Property<String>

  @get:Inject
  abstract val fileSystemOperations: FileSystemOperations

  /**
   * 原子构建本次静态发布目录并生成只包含实际资源路径的 package.json。
   *
   * @throws GradleException 源目录为空、包含自行维护的 package.json，或资源复制失败。
   */
  @TaskAction
  fun preparePackage() {
    val sourceRoots = sourceDirectories.files.filter { it.exists() }.sortedBy { it.absolutePath }
    val sourceFilesByPath = linkedMapOf<String, java.io.File>()
    sourceRoots.forEach { sourceRoot ->
      if (!sourceRoot.isDirectory) {
        throw GradleException("Static npm source '${sourceRoot.absolutePath}' must be a directory.")
      }
      sourceRoot.walkTopDown().filter(java.io.File::isFile).forEach { sourceFile ->
        val relativePath = sourceFile.relativeTo(sourceRoot).invariantSeparatorsPath
        if (relativePath == PACKAGE_JSON) {
          throw GradleException(
            "Static npm source '${sourceRoot.absolutePath}' must not contain package.json; " +
                "name and version are generated by manager.npmStatic.",
          )
        }
        val previous = sourceFilesByPath.putIfAbsent(relativePath, sourceFile)
        if (previous != null) {
          throw GradleException(
            "Static npm sources contain duplicate path '$relativePath' in " +
                "'${previous.absolutePath}' and '${sourceFile.absolutePath}'.",
          )
        }
      }
    }
    val output = outputDirectory.get().asFile
    fileSystemOperations.delete { delete(output) }
    fileSystemOperations.copy {
      sourceRoots.forEach(::from)
      into(output)
    }
    val assetPaths = output.walkTopDown()
      .filter { it.isFile }
      .map { it.relativeTo(output).invariantSeparatorsPath }
      .sorted()
      .toList()
    if (assetPaths.isEmpty()) {
      throw GradleException("Static npm resource source set contains no files.")
    }

    val metadata = JsonObject().apply {
      addProperty("name", packageName.get())
      addProperty("version", packageVersion.get())
      add("files", JsonArray().apply { assetPaths.forEach(::add) })
    }
    output.resolve(PACKAGE_JSON).writeText(GSON.toJson(metadata))
  }

  private companion object {
    const val PACKAGE_JSON = "package.json"
    val GSON = GsonBuilder().setPrettyPrinting().create()
  }
}
